registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /cephfs-docker/certs/fullchain.pem
    REGISTRY_HTTP_TLS_KEY: /cephfs-docker/certs/privkey.pem
  volumes:
    - /cephfs-docker:/cephfs-docker
    - /docker-data/registry:/var/lib/registry
