version: '3.6'

services:
  rancher:
    container_name: rancher
    image: rancher/server:stable
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /root/.ssh/:/root/.ssh/
