# Use root/example as user/password credentials
version: '3.6'

services:
  mariadb:
    container_name: mariadb0
    image: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb0vol:/var/lib/mysql
    ports:
      - 3306:3306

  powerdns:
    container_name: pdns_server0
    build: powerdns
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8081:8081

  adminer:
    container_name: adminer0
    image: adminer
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:8080

  pdns_admin:
    container_name: pdns_admin0
    build: pdns_admin
    restart: unless-stopped
    env_file: .env
    volumes:
      - pdnsadmin0vol:/opt/web/pdns-admin

        # apache:
        #   volumes:
        #     - pdnsadmin0vol:/opt/web/pdns-admin
volumes:
  mariadb0vol:
  pdnsadmin0vol:
