version: '3.6'

services:
  dhcpd:
    container_name: dhcpd
    build:
      context: builders/dhcpd-ldap
    image: user/dhcpd-ldap
    environment:
      - DEVEL_MODE=1
      - INTERFACES="eth2"
      - RECONF=1
      - LDAP_SERVER="docker0.alcocer.net"
      - LDAP_USERNAME="cn=dhcpd,ou=Users,dc=alcocer,dc=net"
      - LDAP_BASE_DN="ou=dhcpd,ou=Services,dc=alcocer,dc=net"
    volumes:
      - /root/dhcp/:/etc/dhcp/
    hostname: dhcpd0
    domainname: alcocer.net
    network_mode: "host"
    restart: unless-stopped

