# Use root/example as user/password credentials
version: '3'

services:
  mariadb:
    container_name: mariadb0
    image: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb0vol:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    container_name: adminer0
    image: adminer
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

  powerdns:
    container_name: pdns_server0
    env_file: .env
    build:
      context: ../builders/powerdns
      args:
        - PDNS_DB
        - PDNS_USER
        - PDNS_USER_PASSWD
        - PDNS_API_KEY
        - PDNS_WEB_PORT
        - PDNS_WEB_PASSWD
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:8081"

  powerdns_admin:
    container_name: powerdns_admin0
    build:
      context: ../builders/powerdns-admin
      target: powerdns-admin:my_built
    image: powerdns-admin:my_built
    restart: unless-stopped
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_APP=app/__init__.py
    entrypoint:
      - bin/bash
      - /root/utils/pdns_admin.sh
    ports:
      - "9191:9191"
    depends_on:
      - mariadb

volumes:
  mariadb0vol:
