version: '3.6'

services:
  ldap:
    container_name: ldap
    build:
      context: builders/openldap
    image: user/ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - INIT_DB=1
      - SUFFIX="dc=alcocer,dc=net"
      - ROOTPW="root"
      - ROOTDN="cn=admin,dc=alcocer,dc=net"
    volumes:
      - slapd_db:/etc/openldap/slapd.d

volumes:
  slapd_db:

