# Use root/example as user/password credentials
version: '3.6'

services:
  mariadb:
    container_name: mariadb
    image: bitnami/mariadb
    restart: unless-stopped
    env_file: ./mariadb.env
    volumes:
      - mariadb0vol:/bitnami/mariadb
    ports:
      - "3306:3306"
    networks:
      - powerdns-net

  adminer:
    container_name: adminer0
    image: adminer
    restart: unless-stopped
    env_file: ./pdns.env
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - powerdns-net

  pdns-authserver:
    container_name: pdns_authserver
    env_file: ./pdns.env
    build:
      context: ./builders/pdns-authserver
    image: user/pdns-authserver
    restart: unless-stopped
    entrypoint:
      - /bin/bash
      - /entrypoint.sh
      - start
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:8081"
    depends_on:
      - mariadb
    networks:
      - powerdns-net

networks:
  powerdns-net:
    driver: bridge

volumes:
  mariadb0vol:
